set-option -g prefix C-s
set-option -g default-terminal "tmux-256color" # 256色対応
set-option -gu terminal-features
set-option -sa terminal-features ',*:overline' # 上線を有効化
set-option -sa terminal-features ",*:RGB"
set-option -g allow-passthrough on
set-option -g history-limit 5000
set-option -g repeat-time 5000

# key bind--------------------------------------------------------
bind-key -N "再読み込み" r {
  source-file ~/.config/tmux/.tmux.conf ; \
  display-message "Reload Config!!"
}
bind-key c new-window -c "#{pane_current_path}"
# | でペインを縦に分割する
bind-key | split-window -h -c '#{pane_current_path}'
bind-key \\ split-window -h -c '#{pane_current_path}'

# - でペインを横に分割する
bind-key - split-window -v -c '#{pane_current_path}'

# Vimのキーバインドでペインを移動する
bind-key h if-shell -F '#{pane_at_left}' '' 'select-pane -L'
bind-key j if-shell -F '#{pane_at_bottom}' '' 'select-pane -D'
bind-key k if-shell -F '#{pane_at_top}' '' 'select-pane -U'
bind-key l if-shell -F '#{pane_at_right}' '' 'select-pane -R'

bind-key m display-popup -E -w 80% -h 80% "tmux-session-manager"
bind-key M display-popup -E -w 80% -h 80% "tmux-move-window"
bind-key w {
  display-popup -E -w 80% -h 80% -d '#{pane_current_path}' "tmux-ghq '#{pane_id}'"
  if-shell -F '#{@ghq_cd}' {
    # そのままでは展開されないため、run-shell経由
    run-shell 'tmux send-keys "cd #{@ghq_cd}" Enter'
    set-option -gu @ghq_cd
  }
}

bind-key f display-panes
set-option -g display-panes-time 90000

# M Alt
# -n prefixキーを押さなくて良い
bind-key -n M-p previous-window
bind-key -n M-n next-window
bind-key -n M-k { switch-client -p; refresh-client -S }
bind-key -n M-j { switch-client -n; refresh-client -S }

# ウィンドウの入れ替え
bind-key -n M-h swap-window -t -1 \; previous-window
bind-key -n M-l swap-window -t +1 \; next-window

# 誤爆防止
unbind-key Space # 元 レイアウト変更
unbind-key t # 元 時計表示

# Vimのキーバインドでペインをリサイズする
# -r repeat-timeで指定したミリ秒間prefixを押さずに連続入力できる
bind-key -r H resize-pane -L
bind-key -r J resize-pane -D
bind-key -r K resize-pane -U
bind-key -r L resize-pane -R

bind-key -N "一時的にペインズーム" -n M-z resize-pane -Z

bind-key -N "ペインIDの表示" P {
  if-shell "which xsel" {
    run-shell 'echo "#{pane_id}" | xsel -bo'
    display-message "Buffer pane_id #{pane_id}";
  }
  if-shell "which pbpaste" {
    run-shell 'echo "#{pane_id}" | pbcopy'
    display-message "Buffer pane_id #{pane_id}";
  }
}

# ペインをkillしてカレントディレクトリ維持しつつ再起動
bind-key -N "ペインを再起動" Q respawn-pane -k -c '#{pane_current_path}'
bind-key -N "ペインを再起動" q confirm-before -p "respawn-pane? (y/others)" "respawn-pane -k -c '#{pane_current_path}'"
